"""task foregin key fixed

Revision ID: 0c7bc5fcebcb
Revises: ff84adbef8c3
Create Date: 2024-11-03 07:13:31.429008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7bc5fcebcb'
down_revision: Union[str, None] = 'ff84adbef8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertask', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('usertask', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_usertask_user_id'), 'usertask', ['user_id'], unique=False)
    op.create_foreign_key(None, 'usertask', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'usertask', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertask', type_='foreignkey')
    op.drop_constraint(None, 'usertask', type_='foreignkey')
    op.drop_index(op.f('ix_usertask_user_id'), table_name='usertask')
    op.drop_column('usertask', 'account_id')
    op.drop_column('usertask', 'user_id')
    # ### end Alembic commands ###
