"""task id duplicatin removed

Revision ID: 57011aa9391b
Revises: 5e55a9be3e58
Create Date: 2024-11-03 00:04:09.056273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57011aa9391b'
down_revision: Union[str, None] = '5e55a9be3e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usertask_task_id', table_name='usertask')
    op.drop_column('usertask', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertask', sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_usertask_task_id', 'usertask', ['task_id'], unique=True)
    # ### end Alembic commands ###
