"""task foregin key fixed

Revision ID: ff84adbef8c3
Revises: 57011aa9391b
Create Date: 2024-11-03 07:10:49.238234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff84adbef8c3'
down_revision: Union[str, None] = '57011aa9391b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usertask_user_id', table_name='usertask')
    op.drop_constraint('usertask_account_id_fkey', 'usertask', type_='foreignkey')
    op.drop_constraint('usertask_user_id_fkey', 'usertask', type_='foreignkey')
    op.drop_column('usertask', 'account_id')
    op.drop_column('usertask', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertask', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('usertask', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('usertask_user_id_fkey', 'usertask', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usertask_account_id_fkey', 'usertask', 'account', ['account_id'], ['id'])
    op.create_index('ix_usertask_user_id', 'usertask', ['user_id'], unique=False)
    # ### end Alembic commands ###
