"""schudule time added

Revision ID: ffebc698b29d
Revises: ec3f7bb80b74
Create Date: 2024-11-04 09:16:11.568414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffebc698b29d'
down_revision: Union[str, None] = 'ec3f7bb80b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertask', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertask', 'scheduled_time')
    # ### end Alembic commands ###
